package bb

import (
	"fmt"
	"path/filepath"
	"sort"

	"github.com/jisung9870/binbox-cli/internal/bb/awsbrowser"
)

const zshCompletion = `
# zsh completion generated by bb. Git-related bb commands are intentionally omitted.
_bb_static() {
  local label="$1"
  shift
  local -a values
  values=("$@")
  _describe "$label" values
}

_bb_dynamic() {
  local label="$1"
  shift
  local -a values
  values=("${(@f)$(command bb completion candidates "$@" 2>/dev/null)}")
  (( ${#values} > 0 )) && compadd -J "$label" -- "${values[@]}"
}

_bb() {
  if (( CURRENT == 2 )); then
    _bb_static 'bb command' \
      'version:print version information' \
      'doctor:check external capabilities' \
      'setup:configure shell or editor integration' \
      'shell:print shell integration' \
      'completion:print shell completion' \
      'project:manage local projects' \
      'tm:manage tmux projects and sessions' \
      'kx:run Kubernetes helpers' \
      'assm:open AWS SSM sessions' \
      'aws:authenticate SSO or apply AWS credentials' \
      'assume:compatibility alias for aws assume' \
      'profile:compatibility AWS profile configuration' \
      'wenv:manage environment presets' \
      'sec:manage encrypted secrets' \
      'port:inspect or stop port listeners' \
      'tfx:run guarded Terraform workflows' \
      'tvx:run Trivy policy workflows' \
      'mcp:manage and synchronize MCP servers'
    return
  fi

  case "${words[2]}" in
    completion)
      (( CURRENT == 3 )) && _bb_static 'shell' 'zsh:generate zsh completion'
      ;;
    shell)
      if (( CURRENT == 3 )); then _bb_static 'action' 'init:initialize shell integration'
      elif (( CURRENT == 4 )) && [[ "${words[3]}" == init ]]; then _bb_static 'shell' 'zsh:zsh integration'
      fi
      ;;
    doctor)
      if (( CURRENT == 3 )); then _bb_static 'option' '--json:JSON envelope' 'nvim:inspect Neovim configuration'
      elif [[ "${words[3]}" == nvim ]]; then _bb_static 'option' '--config-dir:configuration directory' '--repository:expected repository' '--revision:expected revision' '--lockfile-sha256:expected lockfile hash' '--headless:run headless check' '--json:JSON envelope'
      fi
      ;;
    setup)
      if (( CURRENT == 3 )); then _bb_static 'target' 'shell:configure zsh startup' 'nvim:configure Neovim'
      elif [[ "${words[3]}" == nvim ]]; then _bb_static 'option' '--config-dir:configuration directory' '--repository:expected repository' '--revision:expected revision' '--lockfile-sha256:expected lockfile hash' '--dry-run:preview setup' '--apply:apply setup' '--consent:confirm link mutation' '--json:JSON envelope'
      fi
      ;;
    project)
      if (( CURRENT == 3 )); then
        _bb_static 'project command' 'list:list projects' 'add:add a project' 'show:show a project' 'remove:remove a project' 'import:import legacy project metadata' '--json:JSON envelope'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          list) _bb_static 'option' '--json:JSON envelope' ;;
          show|remove) _bb_dynamic 'project' project ;;
          add) _directories ;;
          import) _bb_static 'source' 'sessionizer:legacy sessionizer source' ;;
        esac
      fi
      ;;
    tm)
      if (( CURRENT == 3 )); then
        _bb_static 'tm command or option' 'projects:list registered project paths' 'sessions:list tmux sessions' 'attach:attach to a tmux session' 'kill:remove a tmux session' 'dirs:manage project directories' 'layout:create a fixed layout' '--project:select an exact project' '--json:JSON envelope'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          attach) _bb_static 'option' '--session:exact tmux session' ;;
          kill) _bb_static 'option' '--session:exact tmux session' '--yes:skip confirmation' ;;
          dirs) _bb_static 'dirs command' 'list:list paths' 'add:add path' 'remove:remove project' 'prune:remove stale paths' ;;
          layout) _bb_static 'option' '--layout:fixed layout' '--session:tmux session' '--path:working directory' ;;
          --project) _bb_dynamic 'project' project ;;
          projects) _bb_static 'format' '--plain:paths only' '--json:JSON envelope' ;;
          sessions) _bb_static 'format' '--json:JSON envelope' ;;
        esac
      elif (( CURRENT == 5 )); then
        case "${words[3]}:${words[4]}" in
          attach:--session|kill:--session) _bb_dynamic 'tmux session' tmux-session ;;
          layout:--layout) _bb_static 'layout' 'golang:Go development' 'k8s:Kubernetes operations' 'terraform:Terraform operations' ;;
          layout:--session) _bb_dynamic 'tmux session' tmux-session ;;
          layout:--path) _directories ;;
        esac
      fi
      ;;
    wenv)
      if (( CURRENT == 3 )); then
        _bb_static 'wenv command' 'list:list presets' 'current:show current preset' 'show:show preset values' 'apply:apply a preset' 'export:print exports' 'set:set preset values' 'rm:remove a preset' 'import:import legacy presets'
        _bb_dynamic 'environment' wenv
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          show|apply|export|set|rm) _bb_dynamic 'environment' wenv ;;
          import) _bb_static 'mode or option' '--check:preview import' '--apply:apply import' '--dir:legacy directory' ;;
        esac
      elif (( CURRENT == 5 )); then
        case "${words[3]}" in apply|rm) _bb_static 'option' '--yes:skip confirmation' ;; esac
      fi
      ;;
    profile)
      if (( CURRENT == 3 )); then
        _bb_static 'profile command' 'list:list profiles' 'show:show profile' 'add:add profile' 'edit:edit profile' 'rm:remove profile' 'login:run AWS SSO login'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in show|edit|rm|login) _bb_dynamic 'AWS profile' profile ;; esac
      elif (( CURRENT >= 5 )); then
        case "${words[3]}" in
          add|edit) _bb_static 'profile field' '--sso-session:SSO session' '--account-id:AWS account ID' '--role-name:role name' '--region:AWS region' '--sso-start-url:SSO start URL' '--sso-region:SSO region' ;;
          rm) _bb_static 'option' '--yes:skip confirmation' ;;
        esac
      fi
      ;;
    aws)
      if (( CURRENT == 3 )); then
		_bb_static 'AWS command' 'browse:browse read-only AWS resources' 'query:run a scoped read-only query' 'sync:collect an explicit AWS snapshot' 'refs:find snapshot references' 'sso:log in to an SSO session' 'assume:apply profile credentials'
      elif [[ "${words[3]}" == query ]]; then
        if (( CURRENT == 4 )); then
          _bb_static 'AWS query' 'ec2:query EC2 resources' 'domain:find an exact domain' 'role:find an exact IAM role'
        elif [[ "${words[4]}" == ec2 ]]; then
          if (( CURRENT == 5 )); then
            _bb_static 'EC2 query' 'instances:list or find instances in the current context'
          elif [[ "${words[5]}" == instances ]]; then
            case "${words[CURRENT-1]}" in
              --profile) _bb_dynamic 'AWS profile' profile ;;
              --region) ;;
              *) _bb_static 'query option' '--profile:AWS profile' '--region:AWS region' '--json:stable JSON envelope' ;;
            esac
          fi
        elif [[ "${words[4]}" == domain || "${words[4]}" == role ]]; then
          if (( CURRENT >= 6 )); then
            case "${words[CURRENT-1]}" in
              --profile) _bb_dynamic 'AWS profile' profile ;;
              --region) ;;
              --scope) _bb_static 'query scope' 'current:current context only' 'all:all configured profiles' ;;
              *) _bb_static 'query option' '--profile:AWS profile' '--region:AWS region' '--scope:search scope' '--json:stable JSON envelope' ;;
            esac
          fi
        fi
	  elif [[ "${words[3]}" == sync ]]; then
		if (( CURRENT == 4 )); then
		  _bb_static 'snapshot resource' 'sg:security groups'
		elif [[ "${words[4]}" == sg ]]; then
		  case "${words[CURRENT-1]}" in
			--group) _bb_dynamic 'AWS context group' aws-context-group ;;
			*) _bb_static 'sync option' '--group:configured context group' '--json:stable JSON envelope' ;;
		  esac
		fi
	  elif [[ "${words[3]}" == refs ]]; then
		if (( CURRENT == 4 )); then
		  _bb_static 'snapshot resource' 'sg:security groups'
		elif [[ "${words[4]}" == sg ]] && (( CURRENT >= 6 )); then
		  case "${words[CURRENT-1]}" in
			--account|--region|--partition) ;;
			*) _bb_static 'refs option' '--account:12-digit AWS account ID' '--region:AWS region' '--partition:AWS partition' '--json:stable JSON envelope' ;;
		  esac
		fi
	  elif [[ "${words[3]}" == browse ]]; then
        case "${words[CURRENT-1]}" in
          --profile) _bb_dynamic 'AWS profile' profile ;;
          --region) ;;
          *) _bb_static 'browse option' '--profile:AWS profile' '--region:AWS region' ;;
        esac
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          sso)
            _bb_static 'SSO command' 'list:list SSO sessions'
            _bb_dynamic 'AWS SSO session' sso-session
            ;;
          assume)
            _bb_static 'assume command' 'list:list profiles' 'current:show current identity' 'unset:clear credentials' 'exec:run a scoped command'
            _bb_dynamic 'AWS profile' profile
            ;;
        esac
      elif (( CURRENT == 5 )); then
        if [[ "${words[3]}" == assume && "${words[4]}" == exec ]]; then
          _bb_dynamic 'AWS profile' profile
        fi
      fi
      ;;
    assume)
      if (( CURRENT == 3 )); then
        _bb_static 'assume command' 'list:list profiles' 'current:show current identity' 'unset:clear credentials' 'exec:run a scoped command' 'profile:manage profiles'
        _bb_dynamic 'AWS profile' profile
      elif (( CURRENT == 4 )) && [[ "${words[3]}" == exec ]]; then
        _bb_dynamic 'AWS profile' profile
      fi
      ;;
    sec)
      if (( CURRENT == 3 )); then
        _bb_static 'secret command' 'init:initialize encrypted store' 'list:list metadata' 'set:set a value' 'rename:rename a field' 'get:print a value' 'copy:copy a value' 'env:print exports' 'exec:run a scoped command' 'rm:remove metadata'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in list|set|rename|get|copy|env|exec|rm) _bb_dynamic 'secret service' secret-service ;; esac
      elif (( CURRENT == 5 )); then
        case "${words[3]}" in
          set|rename|get|copy|rm) _bb_dynamic 'secret field' secret-field "${words[4]}" ;;
          exec) _bb_static 'separator' '--:end bb options' ;;
        esac
      elif (( CURRENT == 6 )); then
        case "${words[3]}" in set) _bb_static 'option' '--force:replace without confirmation' ;; rm) _bb_static 'option' '--yes:skip confirmation' ;; esac
      elif (( CURRENT == 7 )) && [[ "${words[3]}" == rename ]]; then
        _bb_static 'option' '--yes:skip confirmation'
      fi
      ;;
    port)
      (( CURRENT == 3 )) && _bb_static 'port command' 'inspect:inspect listeners' 'kill:terminate exact listeners' '--json:JSON envelope'
      ;;
    tfx)
      if (( CURRENT == 3 )); then
        _bb_static 'Terraform command' 'init:initialize' 'validate:validate' 'fmt:format' 'plan:create plan' 'sum:summarize plan' 'session:start safety session' 'status:show session status' 'apply:apply plan' 'destroy:destroy resources' 'end:end safety session' 'state:manage state' 'review:review repositories' 'clean:clean artifacts'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          state) _bb_static 'state command' 'list:list addresses' 'show:show address' 'mv:move address' 'rm:remove address' ;;
          sum) _bb_static 'summary format' 'summary:summary' 'tree:tree' 'stree:short tree' 'draw:diagram' 'md:Markdown' 'json:JSON' ;;
          status) _bb_static 'option' '--json:JSON envelope' ;;
        esac
      fi
      ;;
    tvx)
      if (( CURRENT == 3 )); then
        _bb_static 'Trivy command' 'image:scan image' 'repo:scan repository' 'config:scan configuration' 'ci:run fixed CI policy' 'sbom:generate SBOM' 'report:generate report' 'k8s:scan Kubernetes' 'clean:clean cache' 'doctor:inspect Trivy configuration'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in ci) _bb_static 'scan type' 'image:image' 'repo:repository' 'config:configuration' ;; sbom) _bb_static 'scan type' 'image:image' 'repo:repository' ;; report) _bb_static 'format' 'json:JSON' 'sarif:SARIF' ;; esac
      fi
      ;;
    kx)
      if (( CURRENT == 3 )); then _bb_static 'Kubernetes command' 'context:manage contexts' 'namespace:manage namespaces' 'log:stream logs' 'exec:execute in pod' 'port-forward:forward ports'
      elif (( CURRENT == 4 )); then case "${words[3]}" in context|namespace) _bb_static 'action' 'list:list' 'use:use exact name' ;; esac
      fi
      ;;
    assm)
      (( CURRENT == 3 )) && _bb_static 'SSM command' 'shell:start shell session' 'port-forward:start port forwarding'
      ;;
    mcp)
      if (( CURRENT == 3 )); then
        _bb_static 'MCP command' 'list:list servers' 'show:show a server' 'add:add a server' 'edit:edit a server' 'rm:remove a server' 'sync:synchronize a client' 'check:validate registrations' 'audit:audit config metadata'
      elif (( CURRENT == 4 )); then
        case "${words[3]}" in
          show|edit|rm|check) _bb_dynamic 'MCP server' mcp ;;
          sync) _bb_static 'MCP client' 'claude:Claude Code' 'codex:Codex' ;;
          list|audit) _bb_static 'option' '--json:JSON envelope' ;;
          add) _bb_static 'option' '--stdio:stdio command' '--http:streamable HTTP URL' '--description:purpose' '--arg:stdio argument' '--env:required environment name' '--bearer-token-env:bearer token environment name' '--targets:registration targets' ;;
        esac
      elif (( CURRENT == 5 )); then
        case "${words[3]}" in
          sync) _bb_dynamic 'MCP server' mcp ;;
          rm) _bb_static 'option' '--yes:skip confirmation' ;;
          edit) _bb_static 'option' '--stdio:stdio command' '--http:streamable HTTP URL' '--description:purpose' '--arg:replace stdio arguments' '--env:replace required environment names' '--bearer-token-env:bearer token environment name' '--targets:registration targets' '--clear-args:remove arguments' '--clear-env:remove environment names' '--clear-bearer-token-env:remove bearer token environment name' ;;
        esac
      fi
      ;;
    version)
      (( CURRENT == 3 )) && _bb_static 'option' '--json:JSON envelope'
      ;;
  esac
}

if (( ! $+functions[compdef] )); then
  autoload -Uz compinit
  compinit -i
fi
compdef _bb bb
`

func (a *App) completion(args []string) error {
	if helpRequested(args) || len(args) == 0 {
		_, err := fmt.Fprint(a.out, `Usage:
  bb completion zsh

Print native zsh completion. "bb shell init zsh" includes the same completion
automatically. Dynamic candidates contain names and IDs only, never secret
values or AWS credentials.
`)
		return err
	}
	if len(args) == 1 && args[0] == "zsh" {
		_, err := fmt.Fprint(a.out, zshCompletion)
		return err
	}
	if len(args) >= 2 && args[0] == "candidates" {
		return a.printCompletionCandidates(args[1:])
	}
	return usage("completion", "zsh")
}

func (a *App) printCompletionCandidates(args []string) error {
	if len(args) < 1 || len(args) > 2 {
		return usage("completion candidates", "<kind> [parent]")
	}
	values, err := a.completionCandidates(args[0], args[1:])
	if err != nil {
		return err
	}
	values = safeCompletionCandidates(values)
	for _, value := range values {
		if _, err := fmt.Fprintln(a.out, value); err != nil {
			return err
		}
	}
	return nil
}

func (a *App) completionCandidates(kind string, parent []string) ([]string, error) {
	switch kind {
	case "wenv":
		store, _, err := a.loadWenv()
		if err != nil {
			return nil, err
		}
		values := make([]string, 0, len(store.Presets))
		for name := range store.Presets {
			values = append(values, name)
		}
		return values, nil
	case "profile":
		data, err := a.readAWSConfig()
		if err != nil {
			return nil, err
		}
		return profileNames(data), nil
	case "sso-session":
		data, err := a.readAWSConfig()
		if err != nil {
			return nil, err
		}
		return ssoSessionNames(data), nil
	case "aws-context-group":
		configRoot, _, err := a.paths()
		if err != nil {
			return nil, err
		}
		groups, err := awsbrowser.LoadContextGroups(filepath.Join(configRoot, awsbrowser.AWSContextGroupsFilename))
		if err != nil {
			return nil, err
		}
		values := make([]string, len(groups))
		for index, group := range groups {
			values[index] = group.Name
		}
		return values, nil
	case "secret-service":
		data, err := a.readSecrets()
		if err != nil {
			return nil, err
		}
		values := make([]string, 0, len(data))
		for service, fields := range data {
			if len(fields) > 0 {
				values = append(values, service)
			}
		}
		return values, nil
	case "secret-field":
		if len(parent) != 1 {
			return nil, usage("completion candidates secret-field", "<service>")
		}
		data, err := a.readSecrets()
		if err != nil {
			return nil, err
		}
		fields, ok := data[parent[0]]
		if !ok {
			return []string{}, nil
		}
		values := make([]string, 0, len(fields))
		for field := range fields {
			values = append(values, field)
		}
		return values, nil
	case "mcp":
		store, _, err := a.loadMCP()
		if err != nil {
			return nil, err
		}
		values := make([]string, 0, len(store.Servers))
		for name := range store.Servers {
			values = append(values, name)
		}
		return values, nil
	case "project":
		config, _, err := a.paths()
		if err != nil {
			return nil, err
		}
		records, err := loadProjects(filepath.Join(config, "projects.json"))
		if err != nil {
			return nil, err
		}
		values := make([]string, 0, len(records)*2)
		for _, record := range records {
			values = append(values, record.ID, record.Name)
		}
		return values, nil
	case "tmux-session":
		records, err := a.tmSessions()
		if err != nil {
			return nil, err
		}
		values := make([]string, 0, len(records))
		for _, record := range records {
			values = append(values, record.Name)
		}
		return values, nil
	default:
		return nil, invalid("unknown completion candidate kind: " + kind)
	}
}

func safeCompletionCandidates(values []string) []string {
	seen := map[string]bool{}
	result := make([]string, 0, len(values))
	for _, value := range values {
		if value == "" || safeTerminalText(value) != value || seen[value] {
			continue
		}
		seen[value] = true
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}
