package bb

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	zshSetupStart = "# >>> bb shell integration >>>"
	zshSetupLine  = `eval "$(bb shell init zsh)"`
	zshSetupEnd   = "# <<< bb shell integration <<<"
)

const zshInit = `# Generated by "bb shell init zsh". Evaluate this output from .zshrc.
bb() {
  if [[ "${1:-}" == "wenv" ]]; then
    case "${2:-}" in
      list|current|show|export|set|rm|import|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  elif [[ "${1:-}" == "assume" ]]; then
    case "${2:-}" in
      list|current|exec|profile|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  elif [[ "${1:-}" == "aws" && "${2:-}" == "assume" ]]; then
    case "${3:-}" in
      list|current|exec|profile|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  else
    command bb "$@"
  fi
}
` + zshCompletion

func (a *App) shell(args []string) error {
	if helpRequested(args) || len(args) == 0 {
		_, err := fmt.Fprint(a.out, `Usage:
  bb shell init zsh

Print shell integration to stdout. Evaluate it from .zshrc to make
The Apply action in "bb wenv" and "bb aws assume [profile]" update the current
shell without sourcing a checkout. Native zsh completion is registered at the
same time.
`)
		return err
	}
	if len(args) != 2 || args[0] != "init" || args[1] != "zsh" {
		return usage("shell", "init zsh")
	}
	_, err := fmt.Fprint(a.out, zshInit)
	return err
}

func (a *App) setupShell(args []string) error {
	if helpRequested(args) {
		_, err := fmt.Fprintln(a.out, "Usage: bb setup shell")
		return err
	}
	if len(args) != 0 {
		return invalid("usage: bb setup shell")
	}
	path, err := a.zshRCPath()
	if err != nil {
		return err
	}
	changed, err := configureZshRC(path)
	if err != nil {
		return err
	}
	if changed {
		_, err = fmt.Fprintf(a.out, "Configured bb shell integration in %s\n", path)
	} else {
		_, err = fmt.Fprintf(a.out, "bb shell integration already configured in %s\n", path)
	}
	return err
}

func (a *App) zshRCPath() (string, error) {
	dir := a.getenv("ZDOTDIR")
	if dir == "" {
		dir = a.getenv("HOME")
	}
	if dir == "" {
		return "", errors.New("HOME or ZDOTDIR is required to configure zsh")
	}
	return filepath.Join(dir, ".zshrc"), nil
}

func configureZshRC(path string) (bool, error) {
	contents, mode, target, err := readZshRC(path)
	if err != nil {
		return false, err
	}
	if hasZshSetupLine(contents) {
		return false, nil
	}
	if strings.Contains(string(contents), zshSetupStart) || strings.Contains(string(contents), zshSetupEnd) {
		return false, invalid("existing bb shell integration block is incomplete in " + path)
	}

	updated := append([]byte(nil), contents...)
	if len(updated) > 0 {
		if updated[len(updated)-1] != '\n' {
			updated = append(updated, '\n')
		}
		if len(updated) < 2 || updated[len(updated)-2] != '\n' {
			updated = append(updated, '\n')
		}
	}
	updated = append(updated, zshSetupStart+"\n"...)
	updated = append(updated, zshSetupLine+"\n"...)
	updated = append(updated, zshSetupEnd+"\n"...)
	if err := writeZshRC(target, updated, mode); err != nil {
		return false, fmt.Errorf("configure zsh startup file: %w", err)
	}
	return true, nil
}

func readZshRC(path string) ([]byte, os.FileMode, string, error) {
	target := path
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, 0o600, target, nil
	}
	if err != nil {
		return nil, 0, "", fmt.Errorf("inspect zsh startup file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		target, err = filepath.EvalSymlinks(path)
		if err != nil {
			return nil, 0, "", fmt.Errorf("resolve zsh startup file: %w", err)
		}
		info, err = os.Stat(target)
		if err != nil {
			return nil, 0, "", fmt.Errorf("inspect zsh startup target: %w", err)
		}
	}
	if !info.Mode().IsRegular() {
		return nil, 0, "", invalid("zsh startup file is not a regular file: " + path)
	}
	contents, err := os.ReadFile(target)
	if err != nil {
		return nil, 0, "", fmt.Errorf("read zsh startup file: %w", err)
	}
	return contents, info.Mode().Perm(), target, nil
}

func hasZshSetupLine(contents []byte) bool {
	for _, line := range strings.Split(string(contents), "\n") {
		if strings.TrimSpace(line) == zshSetupLine {
			return true
		}
	}
	return false
}

func writeZshRC(path string, contents []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".bb-zshrc-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(contents); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	d, err := os.Open(dir)
	if err != nil {
		return err
	}
	defer d.Close()
	return d.Sync()
}
