package bb

import "fmt"

const zshInit = `# Generated by "bb shell init zsh". Evaluate this output from .zshrc.
bb() {
  if [[ "${1:-}" == "wenv" ]]; then
    case "${2:-}" in
      list|current|show|export|set|rm|import|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  elif [[ "${1:-}" == "assume" ]]; then
    case "${2:-}" in
      list|current|exec|profile|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  elif [[ "${1:-}" == "aws" && "${2:-}" == "assume" ]]; then
    case "${3:-}" in
      list|current|exec|profile|help|-h|--help)
        command bb "$@"
        ;;
      *)
        local _bb_output _bb_status
        _bb_output="$(command bb "$@")"
        _bb_status=$?
        (( _bb_status == 0 )) || return "$_bb_status"
        eval "$_bb_output"
        ;;
    esac
  else
    command bb "$@"
  fi
}
` + zshCompletion

func (a *App) shell(args []string) error {
	if helpRequested(args) || len(args) == 0 {
		_, err := fmt.Fprint(a.out, `Usage:
  bb shell init zsh

Print shell integration to stdout. Evaluate it from .zshrc to make
The Apply action in "bb wenv" and "bb aws assume [profile]" update the current
shell without sourcing a checkout. Native zsh completion is registered at the
same time.
`)
		return err
	}
	if len(args) != 2 || args[0] != "init" || args[1] != "zsh" {
		return usage("shell", "init zsh")
	}
	_, err := fmt.Fprint(a.out, zshInit)
	return err
}
